on:
  push:
    branches:
    - main
jobs:
  job1:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
        
      - name: Update the README locally
      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          for changed_file in ${{ steps.outputs.new }}; do
              echo "|${changed_file}|description|dependencies|options|${{ steps.date.outputs.date }}|" >> README.md
              echo "|${changed_file}|description|dependencies|options|${{ steps.date.outputs.date }}|"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "daman20"
          git config --global user.email "79991838+daman20@users.noreply.github.com"

          git add -A
          git commit -m "Update README.md with new script"
          git push
