on:
  push:
    branches:
    - main
jobs:
  job1:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
        
      - name: Modifiy the specific files using action
        uses: action-owner/action-repo@ref
# If you execute an action to modify the files, use the 'uses' key.
# Just like as the previous step that executes the checkout action.
# More details, see "https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses"

      - name: Commit and push changes
        run: |
          git config --global user.name "daman20"
          git config --global user.email "79991838+daman20@users.noreply.github.com"

          git add -A
          git commit -m "Update README.md with new script"
          git push
